[package]
name = "Pump Fun"
version = "1.0.0"
authors = ["Taiwo Triumphant"]
upgrade_policy="compatible"

[dependencies]
AptosFramework = { git = "https://github.com/movementlabsxyz/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "movement" }
Pyth = { git = "https://github.com/pyth-network/pyth-crosschain.git", subdir = "target_chains/aptos/contracts", rev = "main" }

[addresses]
pump_fun = "0x3225fcf505c1c418063278d0ff64197464c30a2fa0c0d67412d6c47f5e2a9a67"
pyth="0x9357e76fe965c9956a76181ee49f66d51b7f9c3800182a944ed96be86301e49f"
deployer="0xa3ad2d9c8114b9a4fe97d45b7a9d3c731148d936b0f5dd396fc20a53a11a70da"
wormhole="0x9236893d6444b208b7e0b3e8d4be4ace90b6d17817ab7d1584e46a33ef5c50c9"
